sudo: false
dist: trusty
group: stable

install:
  - pip install --user codecov

language: scala

scala:
  - 2.12.8
  - 2.13.0-RC1
  - 2.11.12
  - 2.10.7
jdk:
  - oraclejdk8

branches:
  only: master

script:
  - scripts/travis-build.sh

before_cache:
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.sbt/boot
