sudo: false
dist: trusty
group: stable

install:
  - pip install --user codecov

language: scala

scala: 2.12.8

jdk:
  - oraclejdk8

branches:
  only: master

script:
  - sbt clean +test

before_cache:
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.sbt/boot
